### ISSUE TITLE
Running Flacoco on Student Projects

### ISSUE THREAD

**Issue by ssk1216** [ASSERT-KTH/flacoco#208]
A folder T1 in which A.java and ATest.java is saved.  I have used the command with the --srcJavaDir and --binJavaDir

>>java -jar target/flacoco-1.0.6-SNAPSHOT-jar-with-dependencies.jar --srcJavaDir F:\T1\src  --srcTestDir  F:\T1\src 
--binJavaDir   F:\T1\bin   --binTestDir   F:\T1\bin

However flacoco is not able to find the test in ATest.java(6 test cases are defined). The output I get is as shown below.

[0] INFO Flacoco - Running Flacoco...
[21] INFO CoverageRunner - Tests found: 0
[21] INFO CoverageRunner - Tests executed: 0

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

I see that you have closed this issue. I hope you managed to fix the issue you were facing.

Let me know if you have any other question regarding flacoco :)

Best,
André

**Comment by ssk1216** [comment]
Hi @andre15silva ,

Many thanks for the reply.  I have fixed it.  

I have some questions; in some cases flacoco points to the line with the class declaration as buggy, however, the bug is in a method in the class.
why is that so?

Can I add Flacco to the CI/CD pipeline?  On commit, Flacco is triggered, and the suspicious lines are listed.  I would like to implement that as part of my project

**Comment by ssk1216** [comment]
As an example,  For this class, the bug is in the line --boolean c=remainder>0.  However, flacoco ranks as follows:
cw_257_1847,2,1.0
cw_257_1847,4,1.0
cw_257_1847,5,1.0
cw_257_1847,6,1.0
cw_257_1847,7,1.0

Why does this happen? 

public class cw_257_1847 {
	boolean productIsEven(int a, int b){
		int product = a*b;
		int remainder = product %2;
		boolean c = remainder>0;
		return c;
	}
}

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

Could you upload the class and tests so that I can try on my side?

Thanks!

**Comment by ssk1216** [comment]
Hi 

I was tested it on  the code I'm https://github.com/ssk1216/CodeWBugs
The test is in the folder productiseven.

I tested it for several code in that folder and have similar results 

Looking forward to for am update

**Comment by ssk1216** [comment]
@andre15silva  , Any updates on my request ?

Thanks again.

**Comment by andre15silva** [comment]
Hi @ssk1216,

I compiled `cw_257_1847` with JUnit 4.13.2 and executed `flacoco` on `cw_257_1847` using the following command:
```bash
java -jar target/flacoco-1.0.6-SNAPSHOT-jar-with-dependencies.jar --binTestDir ~/Repos/CodeWBugs/productIsEven/cw_257_1847_testBin/ --binJavaDir ~/R
epos/CodeWBugs/productIsEven/cw_257_1847_srcBin/ --verbose
```

Note that I separated the java binary directories from the test binary directories, as combining them makes each test appear twice.

I obtained the following result:
```
[0] INFO Flacoco - Running Flacoco...
[1033] INFO CoverageRunner - Tests found: 10
[1034] INFO CoverageRunner - Tests executed: 10
cw_257_1847,2,1.0
cw_257_1847,4,1.0
cw_257_1847,5,1.0
cw_257_1847,6,1.0
cw_257_1847,7,1.0
```

I think the results seem good to me.
The 10 tests where executed, and we obtain the results from each of them.

Now, if you look at the class you see that all lines are executed during each test.
First, line 2 corresponds to the construction of the object during the `setUp`.
The other 4 lines correspond to the method invocation `productIsEven`.

Since all these lines are executed in all tests, it's expected that their suspiciousness values are all the same.
Remember that the suspiciousness value is computed taking into account the coverage information for each line: how many failing tests cover it, how many passing tests cover it, and the number of total tests.
This is known as Spectrum-Based Fault Localization.

Also, note that the file has a blank line before the class begins:
```java

public class cw_257_1847 {
	boolean productIsEven(int a, int b){
		int product = a*b;
		int remainder = product %2;
		boolean c = remainder>0;
		return c;
	}
}
```

**Comment by ssk1216** [comment]
@andre15silva  , Many thanks for the detailed feedback. 
Therefore, if I have to generate hints for the developer based on the above(FL) outputs, then I cannot precisely point at the faulty code, isn't it? 
As most of the lines are included in the list of suspicious code, if an automated program repair tool has to generate a correct patch, then it will be time-consuming (as Multiple patches are to be generated and tested).  Does that mean FL techniques are good for huge programs(with multiple control flows) and not suitable for small programs?  

Is there any documentation available on how to invoke Flacoco as part of  a  CI/CD ?

**Comment by andre15silva** [comment]
> Therefore, if I have to generate hints for the developer based on the above(FL) outputs, then I cannot precisely point at the faulty code, isn't it? 

That is correct yes. flacoco, like any other FL tool, does not always precisely identify the faulty lines.

> As most of the lines are included in the list of suspicious code, if an automated program repair tool has to generate a correct patch, then it will be time-consuming (as Multiple patches are to be generated and tested). Does that mean FL techniques are good for huge programs(with multiple control flows) and not suitable for small programs?

Yes, APR tools are limited by the information from the FL step. If the FL step does not identify the correct line to patch, then the APR tool will not be able to patch it.

And yes, SBFL works better if your program has multiple control flows and a good test suite as it uses the test coverage information and test results to compute a suspiciousness score.
If your program has only one control flow then all lines will be covered by the same number of failing tests and the same number of passing tests, leading to the same suspisciousness score.

> Is there any documentation available on how to invoke Flacoco as part of a CI/CD ?

flacoco is available through a Java API (https://github.com/SpoonLabs/flacoco/wiki#usage-through-the-api) and though a CLI (https://github.com/SpoonLabs/flacoco/wiki#usage-through-the-cli).

It is up to you to decide what fits your design and implementation better.

**Comment by ssk1216** [comment]
@andre15silva ,  That was really helpful, thanks 

 when I run the test , the total number of test shown is 20,instead of 10 (there are only 10 test in total).

I understand, that you did  "Note that I separated the java binary directories from the test binary directories, as combining them makes each test appear twice."  Could you pls let me know what you mean by this?

**Comment by ssk1216** [comment]
@andre15silva , Interesting, Many thanks for the prompt response.

**Comment by ssk1216** [comment]
@andre15silva  , I had run flacoco on all the datasets in this project https://github.com/ssk1216/CodeWBugs.  

My conclusion is that most of these programs are not that complex and do not have major control flows, therefore all the lines have the same suspicious value/do not point to the actual faulty code. 

So does that mean the current FL approaches including Flacoco will work for complex programs only?  OR  Are their any hybrid approaches that can improve the results?  

I work with Fault localization in student programs, and student programming assignments are relatively simpler. 

I am also looking for programming assignment-related datasets to evaluate the FL approaches.

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

> So does that mean the current FL approaches including Flacoco will work for complex programs only? OR Are their any hybrid approaches that can improve the results?

All Spectrum-Based Fault Localization approaches (such as the one implemented in Flacoco) will require multiple tests and control flows to provide valuable results. I am not totally familiar with other FL families however, so I don't really have an answer for you. SBFL is, by far, the most popular technique tho.

Have you taken a look at https://github.com/jkoppel/QuixBugs? Its a dataset from a code competition in both Python and Java. Maybe that dataset could be valuable to you.

https://github.com/Spirals-Team/IntroClassJava is the Java version of IntroClass, which is code written by students. I have not ran SBFL on it, but the projects are likely more complex (albeit not much) than the ones you are using.

**Comment by ssk1216** [comment]
@andre15silva , Thanks for that.  Yes, QuixBugs, and Introclass are the only student programs that are publically available(as far as I know)

I understand that the ranking metric used by Flacoco is Ochiai. I ran the below program and manually calculated the suspicious values and I spot some differences 

// line 1 public class VotingAge {
	public boolean canVote(int x)
	{
//line4		if  (x>18)     // bug is here it is should be x>=18
			return true;
		else
// line 7			return false;
	}
}

----------------------- Test class-------------------
import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

public class VotingAgeTest {
	
	VotingAge obj;
	@Before 
 	public void setUp() throws Exception {
		
		obj=new VotingAge ();
	}
 

	@Test
	public void test1() {
		assertEquals(true,obj.canVote(20) );
		
	}

	@Test
	public void test2() {
		assertEquals(true,obj.canVote(18) );
		
	}

	@Test
	public void test3() {
		assertEquals(false,obj.canVote(10) );
		
	}
}


Formula Ochiai = ef / Squareroot((ef +ep)(ef +nf ))

When I calculated the suspicious score for Line 4,  As there are 3 test in total , ef=2, ep=1,nf=0.
The value is 2/2.4449 =.816

For line 7 ,  it is the same value - .816

However running flacoco , the results are different. Hope I'm not doing anything wrong????

[0] INFO Flacoco - Running Flacoco...
[372] INFO CoverageRunner - Tests found: 3
[372] INFO CoverageRunner - Tests executed: 3
VotingAge,7,0.7071067811865475   
VotingAge,1,0.5773502691896258
VotingAge,4,0.5773502691896258

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

I haven't had time to look at them yet.

I will look at them tomorrow the latest tho.

Best,
André

**Comment by ssk1216** [comment]
@ssk1216 , Many thanks , much appreciated.

**Comment by andre15silva** [comment]
Hi @ssk1216 ,

> When I calculated the suspicious score for Line 4, As there are 3 test in total , ef=2, ep=1,nf=0.

I believe you made a mistake here in your calculations. In your example there are 2 passing tests and 1 failing test.
Hence, ef=1, ep=2, nf=0, np=0 for Line 4.

If you compute Ochiai manually you will get the same result as flacoco does.

> Another question about the above output is class declaration (public class VotingAge) has a suspicious value, but there are no suspicious value calculated for the method signature :public boolean canVote(int x). Why is that so?

I am not sure, as this is due to the underlying instrumentation from JaCoCo. However, I suspect that it may be because the class declaration is "executed" during the object construction.

>  Will that help in an accurate localization ?

I am not familiar with them, so I cannot provide you with any guidance when it comes to that.

>  Also, do you think changing the Ranking metric (from Ochiai) to something else can improve the results?

Changing the ranking metric will change the results, but I am not sure whether you will get better results.
If you want to try out different ranking metrics, you are more than welcome to implement them in flacoco and use it to run them! You can follow what we have done for Ochiai here https://github.com/SpoonLabs/flacoco/tree/master/src/main/java/fr/spoonlabs/flacoco/localization/spectrum/formulas. It should be pretty straight forward to implement a new class from `Formula` and to use it through the config.

**Comment by ssk1216** [comment]
> Hi @ssk1216 ,
> 
> > When I calculated the suspicious score for Line 4, As there are 3 test in total , ef=2, ep=1,nf=0.
> 
> I believe you made a mistake here in your calculations. In your example there are 2 passing tests and 1 failing test. Hence, ef=1, ep=2, nf=0, np=0 for Line 4.
> 
> If you compute Ochiai manually you will get the same result as flacoco does.
> 
> > Another question about the above output is class declaration (public class VotingAge) has a suspicious value, but there are no suspicious value calculated for the method signature :public boolean canVote(int x). Why is that so?
> 
> I am not sure, as this is due to the underlying instrumentation from JaCoCo. However, I suspect that it may be because the class declaration is "executed" during the object construction.
> 
> > Will that help in an accurate localization ?
> 
> I am not familiar with them, so I cannot provide you with any guidance when it comes to that.
> 
> > Also, do you think changing the Ranking metric (from Ochiai) to something else can improve the results?
> 
> Changing the ranking metric will change the results, but I am not sure whether you will get better results. If you want to try out different ranking metrics, you are more than welcome to implement them in flacoco and use it to run them! You can follow what we have done for Ochiai here https://github.com/SpoonLabs/flacoco/tree/master/src/main/java/fr/spoonlabs/flacoco/localization/spectrum/formulas. It should be pretty straight forward to implement a new class from `Formula` and to use it through the config.
> 
> Hope I was able to help you :)


Ya, ya, that was really helpful.   Also , yes the suspicious values are correct (I made a mistake :(). many thanks again!

However, the current suspicious values don't point to the actual buggy code: As in this case it is the If..condition (line4) that is buggy. But the highest suspicious value is allocated for the return statement (line 7)

If this inaccuracy exist ,how can we depend on an FL tool for program repair?

**Comment by andre15silva** [comment]
> If this inaccuracy exist ,how can we depend on an FL tool for program repair?

Depending on FL doesn't mean FL will always be correct. It is one of the components of traditional program repair pipelines and, as with other (e.g. patch generation), it can provide wrong results.

**Comment by ssk1216** [comment]
@andre15silva ,  Many thanks for the suggestions. It was really usefull,

Flacooco has replaced GZolatr in Astor. Is there a  reason why this was done?   Apart from the underlying thirdparty library JaCoCO, Is there any difference in performance as well ?

**Comment by andre15silva** [comment]
> Flacooco has replaced GZolatr in Astor. Is there a reason why this was done? Apart from the underlying thirdparty library JaCoCO & it's usability with newer versions of Java code(> java 8) , Is there any difference in performance as well ?

According to our experiments (https://github.com/flacocobot/flacoco_experiment, paper will be public soon) flacoco is capable of performing fault localization with newer versions of Java code better than GZoltar (e.g. GZoltar does not support Java 17, flacoco does).

We did not analyze "performance" in the sense of actually finding the buggy line because, even with a perfect implementation of SBFL, we are not guaranteed to find the buggy line, since SBFL is not perfect. Thus, we consider finding a valid fault localization result (i.e. non-empty ranked list of locations) as the metric for comparing GZoltar and Flacoco.
