### ISSUE TITLE
Using other formula (Tarantula)

### ISSUE THREAD

**Issue by ashraf04066** [ASSERT-KTH/flacoco#240]
Hello Author,
I have tried to use Tarantula instead of Ochiai. When I applied the law of Tarantula I got the FLACOCO result having the same suspiciousness score for all lines and the score is always '1'. I become surprised to see the output all had the same scores, whereas it was supposed to be having different suspiciousness scores. Here is the code I modified for Tarantula. 
`if ((nFailingExecuting + nFailingNotExecuting == 0) || (nPassingExecuting+nPassingNotExecuting ==0) || ((nFailingExecuting/(nFailingExecuting+nFailingNotExecuting)) + (nPassingExecuting/(nPassingExecuting+nPassingNotExecuting))) == 0) {
			return 0;
		}
return ((nFailingExecuting/(nFailingExecuting+nFailingNotExecuting))
				/ ((nFailingExecuting/(nFailingExecuting+nFailingNotExecuting)) + (nPassingExecuting/(nPassingExecuting+nPassingNotExecuting))));
`
Could you reply to me with the reason for this while using Tarantula?
Thanks in advance!!

**Comment by andre15silva** [comment]
Hi @ashraf04066 ,

Would you be able to open a PR with your Tarantula implementation?
That way I would be able to properly test it.

**Comment by ashraf04066** [comment]
Thank you very much for your quick response. I have created a Pull Request. Please, take a look. More importantly, I'm working with the version1.0.2.

**Comment by andre15silva** [comment]
Hi @ashraf04066,

I replied in your PR. You can use the code in #243 for now. I will merge once I add tests for the tarantula formula.

Btw, any reason why you are using 1.0.2? You can use the latest versions, there have been some bug fixes since 1.0.2 but the interface is the same.

**Comment by ashraf04066** [comment]
Thank you very much for your very quick response. Actually, I have been using FLACOCO since 1.0.2 was released, and I have almost done all of my experiments. Therefore, I'm using the previous version.

**Comment by andre15silva** [comment]
Ah, I see. You can look at the PR and integrate it with 1.0.2 then, it should work ;)

**Comment by ashraf04066** [comment]
It's working nicely. Thank you :)
