### ISSUE TITLE
Flacoco output 

### ISSUE THREAD

**Issue by ssk1216** [ASSERT-KTH/flacoco#245]
Currently Flacoco output the suspicious line and the value .  How can I get the details of the failed test as it only shows the number  of test executed.  How can I know how many out of the tests failed/passed? and the name of the test?
 
[0] INFO Flacoco - Running Flacoco...
[432] INFO CoverageRunner - Tests found: 20
[432] INFO CoverageRunner - Tests executed: 20

**Comment by andre15silva** [comment]
If you use the API, you receive a `FlacocoResult` object that contains more fine-grained information. See[ https://github.com/ASSERT-KTH/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/api/result/FlacocoResult.java](https://github.com/ASSERT-KTH/flacoco/blob/master/src/main/java/fr/spoonlabs/flacoco/api/result/FlacocoResult.java)

Another option would be for you to write your own exporter (https://github.com/ASSERT-KTH/flacoco/tree/master/src/main/java/fr/spoonlabs/flacoco/cli/export), if you want to continue using the CLI.
